### ISSUE TITLE
Working with Apple LLVM 3.1

### ISSUE THREAD

**Issue by wprater** [gcerquant/xcodearchive#10]
Im getting errors with my project that's using the LLVM 3.1 compiler in Xcode 4.3.2.

Should I be getting issues such as these:

```
Check dependencies
2012-04-11 18:42:15.413 xcodebuild[5662:480b] error: Error Domain=NSPOSIXErrorDomain Code=2 "Non-zero exit code 255 returned from shell command: /usr/bin/gcc -v -E -dM -arch armv7 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS5.1.sdk -x objective-c -c /dev/null 2>&1" UserInfo=0x4017e5300 {NSLocalizedDescription=Non-zero exit code 255 returned from shell command: /usr/bin/gcc -v -E -dM -arch armv7 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS5.1.sdk -x objective-c -c /dev/null 2>&1, NSLocalizedFailureReason=No such file or directory}
2012-04-11 18:42:15.421 xcodebuild[5662:480b] Warning:  Couldn't discover the 'gcc' compiler's built-in search paths and preprocessor definitions for language dialect 'objective-c'.
Compiler: /usr/bin/gcc
Reason:   /usr/bin/gcc -v -E -dM -arch armv7 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS5.1.sdk -x objective-c -c /dev/null 2>&1
Warning: Multiple build commands for output file /Users/wprater/Library/Developer/Xcode/DerivedData/Zapd-anddyhqatquuqyeigvcorsjpwpss/Build/Products/Debug-iphoneos/Zapd.app/README.md

... snip

** BUILD FAILED **


The following build commands failed:
    ProcessPCH /Users/wprater/Library/Developer/Xcode/DerivedData/Zapd-anddyhqatquuqyeigvcorsjpwpss/Build/Intermediates/PrecompiledHeaders/Zapd-Prefix-babuooahkhopcvhigosgvoatpjni/Zapd-Prefix.pch.pth Zapd/Zapd-Prefix.pch normal armv7 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)

```

**Comment by gcerquant** [comment]
What happens when you build your project with xcodebuild?

**Comment by wprater** [comment]
Same issue I posted. Xcrun works though. 

Please excuse my brevity; message sent from a mobile device.

**Comment by gcerquant** [comment]
If xcodebuild does not work, then something is wrong with your system. This script is only a wrapper around xcodebuild, xcrun and many system commands.

Wild guess: what happens if you install the Command Line Tools via Xcode (Preferences > Downloads > Components)?

**Comment by wprater** [comment]
I've played around with changing my gcc etc.  I had previously installed gcc-4.2 here: https://github.com/kennethreitz/osx-gcc-installer/downloads and will install Command Line Tools now to see if this fixes it for me.

**Comment by wprater** [comment]
Installing the Command Line Tools let me build with xcodebuild!  Thanks for the tip!

Now I have another issues with multiple iPhone developer identities, but I can fix that by supplying one of them in an argument, I think.

**Comment by gcerquant** [comment]
If it does not fix it, use xcode-select to select the correct dev tools folder.

Also sent from a mobile device, let me know later if you need more details.

**Comment by gcerquant** [comment]
Glad to help :)
Would you mind extracting this information from the ticket and save it for future people with the same issue by creating the proper section in the wiki of the project?

For your duplicate identities, just open Keychain and cleans what need to be.

**Comment by wprater** [comment]
Yeah.. I'll do that!

Also, I have  a pull request coming that allow one to build an ipa from an already packaged .app. :)

Trying to decide if we should require them to specify the mobile_provisioning and developer_identity.  It will archive without them, but they'd never make it into the AppStore?

**Comment by wprater** [comment]
I don't think you have the Wiki enabled?  Or at least Im not able to see it.

Also, I need to keep my multiple identities for multiple projects that we work on I think?

**Comment by gcerquant** [comment]
Can you try again the wiki?

For the multiple identities, usually, if Xcode complains about multiple keys, it generally is possible to delete at least one. But I don't know the details about your system. Be safe by export everything (don't forget the private key), and experiment :)
