### ISSUE TITLE
Why another build script in ruby?

### ISSUE THREAD

**Issue by dodikk** [gcerquant/xcodearchive#6]
Dear gcerquant.
I'm unable to send a private message. That's why I'm opening an issue.

All you are doing in the script is :
1. building an app
2. signing it
3. creating an *.ipa
4. errors reporting / growl integration

Bash already has great tools for the first 3 tasks.
1. "xcodebuild" command. This script forwards a lot of parameters to it.
2. "xcrun" command you are already using.
3. *.ipa can be created easier by plain "zip" tool. See the archive structure below :

YourApp.ipa  ( zip )
   |
   | ---> Payload
   |            |
   |            |-----> YourApp.app

What is the point of creating an "all-in-one" script which only forwards a bunch of parameters to mentioned commands.
Isn't it easier just to use 3 lines of bash instead of 300 lines of ruby?

(ok. with "cd" and "export" commands it may be about 20 lines )

**Comment by dodikk** [comment]
By the way, have you seen an xCode plug-in for Jenkins?
https://wiki.jenkins-ci.org/display/JENKINS/Xcode+Plugin

It has GUI and is easier to use. 
And it's capable of creating nice *.ipa files.

**Comment by dodikk** [comment]
Sorry. I did not mean to be rude here. 
I appreciate the work you've done. 

I'm just curious about its goals as I've encountered some better tools (bash is easier and has even less dependencies, jenkins plug-in is more convenient).

**Comment by gcerquant** [comment]
No offense taken. And I appreciate the interest and help.

The main goal is to use it from the command line, to quickly generate an IPA for any Xcode project.

> What is the point of creating an "all-in-one" script 
> The point is exactly and only that: an "all-in-one" script.
> It mainly forward command to other tools, but it conveniently wraps everything in one tool.

It is easier to type `xcodebuild` than 20 lines of bash from memory.

The fact that you asked the question shows that maybe the README file is not very clear. If you have any improvements to make to it, I would love to receive them.

I'm closing this issue, but feel free to ask any more questions on this thread.

**Comment by gcerquant** [comment]
Actually, I realized I had not yet written a README file. I'm opening a new issue (#7). I would be delighted if you want take care of it.

**Comment by dodikk** [comment]
Well, for my projects I maintain ( at the moment none of them is open source ) I always set up at least three jobs on a build server : 
1. App Store build
2. Ad-hoc build ( for both device and simulator )
3. Unit tests runner ( I use gh-unit )
4. Static analyser build

In case the build server fails ( which is an emergency ) I can choose either of the actions below
1. Run a build script locally
2. Manually run xcodebuild and create an *.ipa package by putting an app to the "Payload" directory and using "compress" option in the Finder.

That's how it works for me. And I'm pretty happy with xcodebuild though.
Your script may simplify a few things for newbies. However, they are going to seek a tool that has GUI (the one similar to the "xCode plug-in" for Jenkins).

**Comment by dodikk** [comment]
I think you are the person who has to write a README.
After all, it's you project - not mine.

Moreover, I won't be able to write a proper README since I don't find this script useful. 
Among advantages I see "errors reporting" and "Growl integration". However, they are not useful for Continuous Integration and will fit into a GUI tool much better.

As an end user I suggest you to think of creating a lightweight GUI on top of this script using "RubyCocoa" or something like it. It must be a lot less complicated than xCode.

**Comment by dodikk** [comment]
There can be some combo-boxes with the list of
- targets
- SDKs
- configurations

Those can be easily retrieved from commands below
"xcodebuild -list"
"xcodebuild -showsdks"

**Comment by dodikk** [comment]
I miss xCode 3.x configurations manager. It looked great and was far more convenient comparing to the one in xCode4.
And it's going to look any better than combo-boxes or table views.

https://github.com/EmbeddedSources/iOS-articles/raw/master/3-iContiniousIntegration/images-presentation/17-BuildOptionsDevice.png
